version: '3.2'

services:
  db:
    image: mysql:8.0
    container_name: appsDB
    restart: always
    ports:
      - '6603:3306'
    environment:
      MYSQL_ROOT_PASSWORD: helloworld

  app:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - '82:80'
    environment:
      - UPLOAD_LIMIT=10G
      - PMA_ARBITRARY=1
      - PMA_HOST=db